[package]
name = "stage-collision"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bitflags = "2.4.1"
parry2d = "0.13"
smallvec = "1.11.2"
